name: title_widget
description: >-
  A widget for visualizing a customizable title with glass effect, gradient,
  rounded corners or/and free shape.
repository: https://github.com/signmotion/title
topics:
  - title
  - glass
  - effects
  - clip
  - widget

# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.3.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  glass: ^1.0.2+1

dev_dependencies:
  flutter_lints: ^3.0.1
  lints: ^3.0.0
  test: ^1.25.2

flutter:
  uses-material-design: true
